#!/bin/bash

KEYDIR="keys"

# frontend
DIR="frontend"
DIRPATH="${KEYDIR}/${DIR}"
rm -rf ${DIRPATH}
mkdir -pv ${DIRPATH}
openssl req \
  -nodes \
  -x509 \
  -newkey rsa:2048 \
  -keyout ${DIRPATH}/key.pem \
  -out ${DIRPATH}/cert.pem \
  -days 365
